### ISSUE TITLE
Progress indicator needed

### ISSUE THREAD

**Issue by Dither** [x64dbg/StaticAnalysis#3]
Because now it's difficult to differentiate between simply hanging x64dbg and the plugin doing some proper work.

**Comment by tr4ceflow** [comment]
I drop the development of this plugin, since I will create a more powerful and smart analysis that will support a GraphView like IDA has.

see my last tweet:
https://twitter.com/tr4ceflow/
or:
http://blog.tr4ceflow.com/sonstiges/smartanalysis.html
and the current dev branch

**Comment by Dither** [comment]
That's great, thank you for the info.
